### DISCUSSION TITLE
ui modal: overflow indicator

### DISCUSSION THREAD

**Discussion by cooper-joe** [dhis2/notes#250] [Ideas]
### The problem
An issue has come up a handful of times that a user doesn't realize there is more content inside a scrollable modal. This happens when the content overflows the boundary at a gap between items, so there isn't the cut-off item to give the "there's more below" hint. This is especially a problem on operating systems/browsers that encourage hiding of scrollbars.

### An idea for a solution
I've been experimenting with the idea of adding an overflow indicator that is more prominent than a scrollbar (or, actually visible when scrollbars are default hidden). The indicator would be a fading-transparent overlay at the bottom of the visible area. Content near the bottom of the visible area would be slightly faded and give a clear indicator that there is more to be found beyond the visible area.

I've naively tested the idea using css `mask-image`, and I think it works visually:

![image](https://user-images.githubusercontent.com/33054985/111642080-10e7c600-87fe-11eb-9ded-fd649fc4f7b6.png)

However, this impementation has issues. The bottom of the scrollbar also gets overlaid by the fade. This would obscure interactive areas of the scrollbar. The content also requires a `padding-bottom`, which may look awkward on non-scrolling modals.

### Questions
Before I think more about this and whether it would work UX-wise, I want to determine the technical feasibility of this idea, the questions are:
- could the faded-bottom-on-overflow idea be technically implemented in another way that avoids the problems noted above?
- are there other reasons, such as accessibility or technical challenges, why this is not a good idea?

Input and feedback appreciated, thanks.

---
For reference, the above was achieved with the following css changes to `ModalContent.js`:

```css
div {
    flex-grow: 1;
    margin: ${spacers.dp24} 0;
    padding: 0 ${spacers.dp24};
    overflow-y: auto;
    -webkit-mask-image: linear-gradient(
        to bottom,
        white 80%,
        transparent 100%
    );
    mask-image: linear-gradient(
        to bottom,
        white 80%,
        transparent 100%
    );
}
div::after {
    content: '';
    display: block;
    padding: ${spacers.dp24};
}
```

**Comment by mediremi** [comment]
I think having a thin border above the action buttons might help as it is likely that some of the text will be partially obscured, encouraging the user to scroll down.

![image](https://user-images.githubusercontent.com/4295266/111645809-fe1ec280-87f8-11eb-8502-8d2da4f428b7.png)

**Reply by cooper-joe** [reply]
The problem I saw with solutions like this: how do we prevent the "overflow indicator" (in this case, the border and dark shadow) from showing when there is no overflow? The above solution is intentionally invisible if there is no overflow. 

We could detect overflow and only show the overlay based on that, but I feel like that is slightly heavy-handed.

The border is also rather small, which means that it will more easily be placed between two components, which won't actually provide the intended effect of hinting at "more overflow content below".

**Reply by KaiVandivier** [reply]
It might be a bit much to detect overflow and show the gradient in just this one application, but maybe that could become a 'ScrollBox' helper component that could be reused a few times? I think it could also be useful in the Tab Bar (maybe) and the Data Table that Hendrik is working on when it's scrollable

I'm sure it would also be useful for other applications down the line too

**Reply by KaiVandivier** [reply]
Or maybe extend the existing 'Box' to hint at extra content when it's scrollable

**Reply by cooper-joe** [reply]
@KaiVandivier, that's an intriguing idea! Do you think there's any way around the issue where the gradient-overlay obscures the bottom of the scrollbar area?

**Reply by KaiVandivier** [reply]
Not sure off the top of my head 🤔 but I'll experiment with it!

**Reply by KaiVandivier** [reply]
I haven't yet nailed down a way to get the fade to white to work perfectly, but I did want to report that one way people have solved this (using only CSS) is to use a radial shadow and some other neat tricks ([article](https://lea.verou.me/2012/04/background-attachment-local/)). Here's a tool to generate CSS to that effect: [tool](https://css-scroll-shadows.now.sh/?bgColor=ffffff&shadowColor=222222&pxSize=10). It looks decent:

<img width="428" alt="scroll-shadows" src="https://user-images.githubusercontent.com/49666798/112041947-3f8bd680-8b47-11eb-9877-8d50b376285c.png">

Code: 
```css
div {
    flex-grow: 1;
    margin: ${spacers.dp24} 0;
    padding: 0 ${spacers.dp24};
    overflow-y: auto;

    background: 
        linear-gradient(#ffffff 33%, rgba(255,255,255, 0)),
        linear-gradient(rgba(255,255,255, 0), #ffffff 66%) 0 100%,
        radial-gradient(farthest-side at 50% 0, rgba(17,17,17, 0.5), rgba(0,0,0,0)),
        radial-gradient(farthest-side at 50% 100%, rgba(17,17,17, 0.5), rgba(0,0,0,0)) 0 100%;
    background-color: #ffffff;
    background-repeat: no-repeat;
    background-attachment: local, local, scroll, scroll;
    background-size: 100% 24px, 100% 24px, 100% 8px, 100% 8px;
}
```
